### ISSUE TITLE
Add new features

### ISSUE THREAD

**Issue by thomasarsouze** [openalea/action-build-publish-anaconda#3]
We want to add new functionalities to this action:
- [x] Don't stop all the jobs of the matrix (os x python-version) when one fails.
- [ ] Possibility to use mamba rather than conda.
- [x] Possiblity to adapt the matrix (os x python-version) depending on the action that launches it (e.g. one os x one python-version when on some dev branch).
- [x] Possibility to upload / publish the package to anaconda only on some cases.

**Comment by thomasarsouze** [comment]
Test are made on a dedicated branch of openalea-incubator/oawidgets

**Comment by thomasarsouze** [comment]
>  Don't stop all the jobs of the matrix (os x python-version) when one fails.

This is actualy not done in the action itself but rather setting `job.strategy.fail-fast` to `false` in the workflow definition file for each package. Cf. also the updated README in the associated branch.

```
jobs:
...
    strategy:
      fail-fast: false
...
```

> Possiblity to adapt the matrix (os x python-version) depending on the action that launches it (e.g. one os x one python-version when on some dev branch).

This is also actualy not done in the action itself but rather in the workflow definition file for each package, when defining the matrix. The code example is (cf. also the updated README in the associated branch) .

```
      matrix:
        os: [ ubuntu-latest , macos-latest , windows-latest]
        python-minor-version: [7, 8, 9]
        isMaster:
          - ${{ github.ref == 'refs/heads/master' }}
        exclude:
          - isMaster: false
            os: ubuntu-latest
            python-minor-version: 7
          - isMaster: false
            os: ubuntu-latest
            python-minor-version: 8
          - isMaster: false
            os: macos-latest
            python-minor-version: 7
          - isMaster: false
            os: macos-latest
            python-minor-version: 8
          - isMaster: false
            os: macos-latest
            python-minor-version: 9
          - isMaster: false
            os: windows-latest
            python-minor-version: 7
          - isMaster: false
            os: windows-latest
            python-minor-version: 8
          - isMaster: false
            os: windows-latest
            python-minor-version: 9            
```

**Comment by thomasarsouze** [comment]
> Possibility to upload / publish the package to anaconda only on some cases.

A dedicated input `publish` is added in the action:
```
    - name: Build and Publish
      uses: openalea/action-build-publish-anaconda@v0.1.1
      with:
         publish: true
         ...
```

Also, in the workflow definition of each package, we can use a condtional switch for uploading only on dedicated conditions (in this case, when the push from branch name includes `stable` or `v***`):
```
    - name: Determine publish
      uses: haya14busa/action-cond@v1
      id: publish
      with:
        cond: ${{ contains(github.ref, 'stable') || startsWith(github.ref, 'refs/heads/v') }}
        if_true: 'true'
        if_false: 'false'
    - name: Build and Publish
      ...
      with:
        publish: ${{ steps.publish.outputs.value }}
        ...
```

**Comment by thomasarsouze** [comment]
> Possibility to use mamba rather than conda.

We define a conditional use of the setup-miniconda action associated with the input value of our action. This means some code duplication but I can't see another easy solution.

```
  - name: Setup Conda environment
    uses: conda-incubator/setup-miniconda@v2
    if: ${{ inputs.mamba }} != true
    with:
      python-version: 3.${{ inputs.python }}
      channels: ${{ inputs.channels }}
      auto-update-conda: false        
  - name: Setup Mamba environment
    uses: conda-incubator/setup-miniconda@v2
    if: ${{ inputs.mamba }} == true
    with:
      python-version: 3.${{ inputs.python }}
      channels: ${{ inputs.channels }}
      auto-update-conda: false
      mamba-version: "*"     
```
